server {
    listen 80;
    server_name map.mc.rushrage.com;

    # Allow Let's Encrypt certificate renewal.
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect HTTP to HTTPS.
    location / {
        return 301 https://$host$request_uri;
    }
}


server {
    listen 443 ssl;
    server_name map.mc.rushrage.com;

    # Let's Encrypt certificate.
    ssl_certificate /etc/letsencrypt/live/map.mc.rushrage.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/map.mc.rushrage.com/privkey.pem;

    location / {
        proxy_pass http://192.168.0.41:31476;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support.
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
